require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/recipes", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Recipe. As you add validations to Recipe, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Recipe.create! valid_attributes
      get recipes_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      recipe = Recipe.create! valid_attributes
      get recipe_url(recipe)
      expect(response).to be_successful
    end
  end

  # describe "GET /new" do
  #   it "renders a successful response" do
  #     get new_recipe_url
  #     expect(response).to be_successful
  #   end
  # end

  # describe "GET /edit" do
  #   it "renders a successful response" do
  #     recipe = Recipe.create! valid_attributes
  #     get edit_recipe_url(recipe)
  #     expect(response).to be_successful
  #   end
  # end

  # describe "POST /create" do
  #   context "with valid parameters" do
  #     it "creates a new Recipe" do
  #       expect {
  #         post recipes_url, params: { recipe: valid_attributes }
  #       }.to change(Recipe, :count).by(1)
  #     end

  #     it "redirects to the created recipe" do
  #       post recipes_url, params: { recipe: valid_attributes }
  #       expect(response).to redirect_to(recipe_url(Recipe.last))
  #     end
  #   end

  #   context "with invalid parameters" do
  #     it "does not create a new Recipe" do
  #       expect {
  #         post recipes_url, params: { recipe: invalid_attributes }
  #       }.to change(Recipe, :count).by(0)
  #     end

  #     it "renders a response with 422 status (i.e. to display the 'new' template)" do
  #       post recipes_url, params: { recipe: invalid_attributes }
  #       expect(response).to have_http_status(:unprocessable_content)
  #     end
  #   end
  # end

  # describe "PATCH /update" do
  #   context "with valid parameters" do
  #     let(:new_attributes) {
  #       skip("Add a hash of attributes valid for your model")
  #     }

  #     it "updates the requested recipe" do
  #       recipe = Recipe.create! valid_attributes
  #       patch recipe_url(recipe), params: { recipe: new_attributes }
  #       recipe.reload
  #       skip("Add assertions for updated state")
  #     end

  #     it "redirects to the recipe" do
  #       recipe = Recipe.create! valid_attributes
  #       patch recipe_url(recipe), params: { recipe: new_attributes }
  #       recipe.reload
  #       expect(response).to redirect_to(recipe_url(recipe))
  #     end
  #   end

  #   context "with invalid parameters" do
  #     it "renders a response with 422 status (i.e. to display the 'edit' template)" do
  #       recipe = Recipe.create! valid_attributes
  #       patch recipe_url(recipe), params: { recipe: invalid_attributes }
  #       expect(response).to have_http_status(:unprocessable_content)
  #     end
  #   end
  # end

  describe "DELETE /destroy" do
    it "destroys the requested recipe" do
      recipe = Recipe.create! valid_attributes
      expect {
        delete recipe_url(recipe)
      }.to change(Recipe, :count).by(-1)
    end

    it "redirects to the recipes list" do
      recipe = Recipe.create! valid_attributes
      delete recipe_url(recipe)
      expect(response).to redirect_to(recipes_url)
    end
  end

  describe "GET /recipes/search" do
    include SignInHelper

    let(:user) { FactoryBot.create(:user, active: true) }

    before do
      sign_in_as(user)
    end

    context "when AI service raises ApiKeyError" do
      before do
        allow_any_instance_of(AiService).to receive(:generate_embedding)
          .and_raise(AiService::ApiKeyError.new("API key not configured"))
      end

      it "renders index with error message" do
        get search_recipes_url, params: { q: "chicken" }
        expect(response).to have_http_status(:success)
        expect(flash.now[:alert]).to include("AI search is not configured")
      end
    end

    context "when AI service raises RateLimitError" do
      before do
        allow_any_instance_of(AiService).to receive(:generate_embedding)
          .and_raise(AiService::RateLimitError.new("Rate limit exceeded"))
      end

      it "renders index with error message" do
        get search_recipes_url, params: { q: "chicken" }
        expect(response).to have_http_status(:success)
        expect(flash.now[:alert]).to include("rate limits")
      end
    end

    context "when AI service raises NetworkError" do
      before do
        allow_any_instance_of(AiService).to receive(:generate_embedding)
          .and_raise(AiService::NetworkError.new("Connection failed"))
      end

      it "renders index with error message" do
        get search_recipes_url, params: { q: "chicken" }
        expect(response).to have_http_status(:success)
        expect(flash.now[:alert]).to include("Unable to connect")
      end
    end

    context "when AI service raises generic Error" do
      before do
        allow_any_instance_of(AiService).to receive(:generate_embedding)
          .and_raise(AiService::Error.new("Service unavailable"))
        allow(Rails.logger).to receive(:error)
      end

      it "renders index with generic error message" do
        get search_recipes_url, params: { q: "chicken" }
        expect(response).to have_http_status(:success)
        expect(flash.now[:alert]).to include("temporarily unavailable")
      end

      it "logs the error" do
        get search_recipes_url, params: { q: "chicken" }
        expect(Rails.logger).to have_received(:error).with(/AI search error/)
      end
    end
  end
end
